pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=Build (10.x)"
      - "check-success=Build (12.x)"
      - "check-success=Build (14.x)"
    actions:
      merge:
        method: squash
