name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verison: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-verison: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
